compile:
	g++ new_grasp.cpp -o new_grasp

run:
	./new_grasp $(alfa) < Instancias/inst$(num_instancia).txt

run_mini_entrada1:
	./new_grasp 0.33 < Instancias/mini_en.txt

run_mini_entrada2:
	./new_grasp 0.33 < Instancias/mini_en2.txt

